---
abstract: 'Utility to extract a name from a PPI Document'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Test::More: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.009, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: PPIx-DocumentName
provides:
  PPIx::DocumentName:
    file: lib/PPIx/DocumentName.pm
    version: '0.001003'
requires:
  Carp: '0'
  PPI::Util: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/kentnl/PPIx-DocumentName/issues
  homepage: https://github.com/kentnl/PPIx-DocumentName
  repository: https://github.com/kentnl/PPIx-DocumentName.git
version: '0.001003'
